---
- name: Install Vscodium
  become: true
  block:
    - name: Verify target is Fedora
      ansible.builtin.assert:
        that:
          - ansible_facts.distribution == "Fedora"
        fail_msg: "This task file is intended for Fedora hosts only."
        quiet: true

    - name: Import VSCodium repository GPG key
      ansible.builtin.rpm_key:
        key: "https://repo.vscodium.dev/vscodium.gpg"
        state: present

    - name: Configure VSCodium RPM repository
      ansible.builtin.yum_repository:
        name: vscodium
        description: "VSCodium Repo"
        baseurl: "https://repo.vscodium.dev/rpm"
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: "https://repo.vscodium.dev/vscodium.gpg"
        metadata_expire: "1h"
        file: vscodium

    - name: Install VSCodium
      ansible.builtin.dnf:
        # name: "{{ vscodium_package | default('codium') }}"
        name: codium
        state: present
        update_cache: true
