---
# gnome shell extension settings
extensions_dconf_files:
  - { src: "dash-to-dock.dconf", root: "/org/gnome/shell/extensions/dash-to-dock/" }
  - { src: "ding.dconf", root: "/org/gnome/shell/extensions/ding/" }
  - { src: "tiling-assistant.dconf", root: "/org/gnome/shell/extensions/tiling-assistant/" }
  - { src: "blur-my-shell.dconf", root: "/org/gnome/shell/extensions/blur-my-shell/" }