---
- name: Install dnf packages
  become: true
  ansible.builtin.dnf:
    state: present
    update_cache: true
    name:
      # tailscale stuff
      - tailscale
      - trayscale
      # misc dev applications
      - rpi-imager
      # desktop applications
      - gimp
      - inkscape
      - xournalpp
      - remmina
      # gnome customizations
      - gnome-tweaks
      - gnome-extensions-app
      - papirus-icon-theme
      # gnome shell extensions
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-no-overview
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-blur-my-shell

- name: Remove unneeded packages
  become: true
  ansible.builtin.dnf:
    state: absent
    update_cache: true
    name:
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list

- name: Install dmz cursor theme
  become: true
  block:
    - name: Install dnf-plugins-core for COPR support
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Enable COPR repository for dmz-cursor-themes
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: madoka241/dmz-cursor-themes

    - name: Install dmz-cursor-themes package
      ansible.builtin.dnf:
        name: dmz-cursor-themes
        state: present


- name: Install flatpak apps
  become: true
  community.general.flatpak:
    state: present
    method: system
    name:
      - io.github.spacingbat3.webcord
      - org.audacityteam.Audacity
      - org.darktable.Darktable
      - org.signal.Signal
      - com.bitwarden.desktop
      - sh.loft.devpod
      - com.moonlight_stream.Moonlight
      - com.transmissionbt.Transmission
      - io.freetubeapp.FreeTube
      - org.chromium.Chromium
      - org.freecad.FreeCAD
