#SPDX-License-Identifier: MIT-0
---
# tasks file for workstation-personalized
# application setup
- import_tasks: install_packages.yml
# gnome customization
- import_tasks: gnome-customizations.yml
- import_tasks: configure-gnome-extensions.yml
- import_tasks: external-gnome-extensions.yml
- import_tasks: gnome-pinned-apps.yml

# shell customization
- import_tasks: copy-bashrc.yml
