---
applications_packages:
  system_utils:
    - vim
    - gcc-c++          # replaces "g++"
    - clang
    - clang-tools-extra
    - cmake
    - cargo
    - python3-pip
    - ffmpeg-free      # Fedora build
    - ImageMagick
    - lz4
    - rsync
    - mediainfo
    - neofetch
    - SFML-devel
    - yt-dlp
    - lm_sensors
    - qemu

  applications:
    - dconf-editor
    - corectrl
    - baobab
    - gparted
    - gsmartcontrol
    - timeshift
    - vlc
    - okular
    - rhythmbox

  gnome_shell_extensions:
    - gnome-tweaks
    - gnome-extensions-app
    - papirus-icon-theme
    - gnome-shell-extension-user-theme
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-gsconnect
    - gnome-shell-extension-no-overview

  misc:
    - texlive
    - piper
    - blender
    - kdenlive
    - epiphany
    - chromium
    - gimp
    - easyeffects
    - inkscape
    - virt-manager

  rpmfusion:
    - v4l2loopback

# Single flattened list used by the dnf task above
applications_packages_all: >-
  {{
    applications_packages.system_utils
    + applications_packages.applications
    + applications_packages.gnome_shell_extensions
    + applications_packages.misc
    + applications_packages.rpmfusion
  }}

# Flatpak configuration
applications_flatpak_method: "user"  # user|system
applications_flatpak_remote_name: "flathub"
applications_flatpak_remote_url: "https://flathub.org/repo/flathub.flatpakrepo"

applications_flatpak_apps:
  - com.github.tchx84.Flatseal
  - com.usebottles.bottles
  - io.github.spacingbat3.webcord
  - org.audacityteam.Audacity
  - org.darktable.Darktable
  - org.signal.Signal
