---
applications_packages:
  system_utils:
    - vim
    - gcc-c++
    - clang
    - clang-tools-extra
    - cmake
    - cargo
    - ffmpeg
    - ImageMagick
    - lz4
    - rsync
    - mediainfo
    - fastfetch
    - lm_sensors
    - qemu
    - v4l2loopback
    - neovim
    - htop
    - gdb
    - distrobox
    - pdftk-java
    - powertop
    - python3-pip
    - python3-virtualenv
    - nmap
    - screen

  applications:
    - dconf-editor
    - baobab
    - gsmartcontrol
    - vlc
    - okular
    - rhythmbox
    - gparted
    - libreoffice
    - gnome-boxes

# Single flattened list used by the dnf task above
applications_packages_all: >-
  {{
    applications_packages.system_utils
    + applications_packages.applications
  }}

# Flatpak configuration
applications_flatpak_method: "system"  # user|system
applications_flatpak_remote_name: "flathub"
applications_flatpak_remote_url: "https://flathub.org/repo/flathub.flatpakrepo"

applications_flatpak_apps:
  - com.github.tchx84.Flatseal
  - com.usebottles.bottles
  - io.github.spacingbat3.webcord
  - org.audacityteam.Audacity
  - org.darktable.Darktable
  - org.signal.Signal
  - com.github.wwmm.easyeffects
