---
applications_packages:
  system_utils:
    - vim
    - gcc-c++
    - clang
    - clang-tools-extra
    - cmake
    - cargo
    - python3-pip
    - ffmpeg
    - ImageMagick
    - lz4
    - rsync
    - mediainfo
    - fastfetch
    - lm_sensors
    - qemu
    - v4l2loopback
    - tailscale

  applications:
    - dconf-editor
    - baobab
    - gsmartcontrol
    - timeshift
    - vlc
    - okular
    - rhythmbox

  gnome_shell_extensions:
    - gnome-tweaks
    - gnome-extensions-app
    - papirus-icon-theme
    - gnome-shell-extension-user-theme
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-gsconnect
    - gnome-shell-extension-no-overview

  misc:
    - epiphany
    - gimp
    - inkscape

# Single flattened list used by the dnf task above
applications_packages_all: >-
  {{
    applications_packages.system_utils
    + applications_packages.applications
    + applications_packages.gnome_shell_extensions
    + applications_packages.misc
  }}

# Flatpak configuration
applications_flatpak_method: "system"  # user|system
applications_flatpak_remote_name: "flathub"
applications_flatpak_remote_url: "https://flathub.org/repo/flathub.flatpakrepo"

applications_flatpak_apps:
  - com.github.tchx84.Flatseal
  - com.usebottles.bottles
  - io.github.spacingbat3.webcord
  - org.audacityteam.Audacity
  - org.darktable.Darktable
  - org.signal.Signal
  - com.github.wwmm.easyeffects
